import type { Case } from "../types";

// Culprit: Dr. Alistair Finch (C1).
// Chain: half-burned letter threatens the Medical Council (E1) + digitalis, which nobody in the house is
// prescribed (E2) -> Margaret saw Finch enter the study 21:50-22:00 -> Mrs. Hodge gave him matches at
// 22:25 -> the Colonel says Finch left the card game twice.
export const blackwoodManor: Case = {
  id: "blackwood-manor",
  title: "Murder at Blackwood Manor",
  description:
    "Lord Edmund Blackwood was found dead in his locked study at 23:00, slumped over his desk beside a broken brandy glass. The storm had cut the manor off from the village. The killer is still in the house.",
  setting: "Blackwood Manor, a country house on a stormy night",
  victim: "Lord Edmund Blackwood",
  timeline: { start: "21:00", end: "23:00" },
  evidence: [
    {
      id: "E1",
      title: "Half-burned note",
      text: "A half-burned letter in the study fireplace, in Lord Blackwood's handwriting: '...if you do not stop at once, I shall inform the Medical Council on Monday. E.B.'",
      kind: "key",
      explanation: "Edmund's letter to Dr. Finch, threatening to expose his forged prescriptions. Finch tried to burn it, but the fire was dying.",
    },
    {
      id: "E2",
      title: "Broken brandy glass",
      text: "A broken brandy glass beside the desk. The spilled brandy contains digitalis, a prescription heart drug. Nobody in the household is prescribed it.",
      kind: "key",
      explanation: "Finch carries digitalis in his medical bag. He dosed the brandy during his 'consultation' at 21:50.",
    },
    {
      id: "E3",
      title: "Stopped clock",
      text: "The study's mantel clock stopped at 10:23 PM.",
      kind: "ambiguous",
      explanation: "It simply ran down. Mrs. Hodge forgot to wind it this week. Edmund actually died at around 22:10.",
    },
    {
      id: "E4",
      title: "Muddy footprint",
      text: "A large muddy footprint, a man's size 10, on the flagstones outside the study's French window. The window was found ajar.",
      kind: "red_herring",
      explanation: "Jasper sneaked out through the study's French window at 21:30 to pay his bookie at the gate, and came back the same way at 22:30.",
    },
    {
      id: "E5",
      title: "The chicken",
      text: "A live chicken was found in the study, sitting calmly on Lord Blackwood's reading chair.",
      kind: "odd",
      explanation: "Duchess, Mrs. Hodge's prize hen. She wandered in through the French window Jasper left ajar.",
    },
  ],
  characters: [
    {
      id: "C1",
      name: "Dr. Alistair Finch",
      blurb: "the family physician and Lord Blackwood's old friend",
      background: "Thirty years as a respected country doctor. For the last two you've been forging prescriptions to sell.",
      relationship: "Edmund was your oldest friend. You play cards with the Colonel.",
      reasonPresent: "Invited to dinner and a private consultation with Edmund.",
      motive: "Edmund found out about the forged prescriptions and wrote that he would report you to the Medical Council on Monday.",
      suspicious: "You carry a medical bag. You were alone with Edmund in the study tonight.",
      secret: null,
      knows: [
        "Jasper has gambling debts. Edmund told you so.",
        "Margaret and Edmund argued loudly after dinner.",
      ],
      culprit: true,
      whatYouDid: [
        "At 21:50 you went to the study for a 'private consultation' and slipped digitalis from your bag into Edmund's brandy.",
        "You rejoined the Colonel's card game in the drawing room at 22:00.",
        "At about 22:25 you asked Mrs. Hodge for matches, went back to the study, found Edmund dead, and burned his letter. The fire was dying and it only half burned.",
        "You were back at the card table by 22:35.",
      ],
      looseEnds: [
        "Margaret may have seen you enter the study.",
        "Mrs. Hodge gave you the matches.",
        "The Colonel knows you left the card game twice.",
        "Digitalis is a doctor's drug.",
      ],
    },
    {
      id: "C2",
      name: "Lady Margaret Blackwood",
      blurb: "Lord Blackwood's wife",
      background: "Twenty-five years married to a cold man.",
      relationship: "Your husband's fortune passes mostly to you.",
      reasonPresent: "It's your home.",
      motive: "You inherit the estate, and your marriage was miserable.",
      suspicious: "You and Edmund argued loudly at 21:30. The whole house heard.",
      secret: "You were planning to leave Edmund. A packed suitcase is hidden in your car. If this comes out, it looks like you were fleeing.",
      knows: [
        "At about 21:50 you saw Dr. Finch go into the study. He came out at about 22:00 looking pale.",
        "After the argument you went up to your room and stayed there until 22:45.",
      ],
      culprit: false,
    },
    {
      id: "C3",
      name: "Jasper Blackwood",
      blurb: "Lord Blackwood's nephew and heir to the title",
      background: "Charming, idle, and in serious trouble.",
      relationship: "Your uncle paid your debts once, and swore never again.",
      reasonPresent: "Staying the weekend, hoping to ask for money.",
      motive: "You inherit the title and some money, and you owe a bookie a fortune.",
      suspicious: "You wear size 10 shoes. The muddy footprint and open French window are yours.",
      secret: "At 21:30 you sneaked out through the study's French window to pay your bookie at the gate, and came back the same way at 22:30. Your uncle was dead at his desk when you came through, and you ran without telling anyone.",
      knows: [
        "When you came back through the study at 22:30, the brandy glass was already broken and your uncle wasn't moving.",
        "Through the window, as you approached, you saw someone crouched at the study fireplace. You couldn't see who.",
      ],
      culprit: false,
    },
    {
      id: "C4",
      name: "Mrs. Hodge",
      blurb: "the Blackwoods' housekeeper",
      background: "You've kept this house running for thirty years.",
      relationship: "You adore Lady Margaret and put up with Lord Edmund.",
      reasonPresent: "You live and work here.",
      motive: "Edmund cut your promised pension last month.",
      suspicious: "You served the brandy. Winding the study clock is your job.",
      secret: null,
      knows: [
        "You served Lord Blackwood's brandy at 21:40, fresh from a sealed bottle.",
        "At about 22:25 Dr. Finch came to the kitchen and asked for a box of matches. You thought it odd.",
        "You forgot to wind the study clock this week. Duchess the hen keeps escaping.",
      ],
      culprit: false,
    },
    {
      id: "C5",
      name: "Colonel Reginald Pike",
      blurb: "Lord Blackwood's old army friend and houseguest",
      background: "Retired, bluff, and fond of cards.",
      relationship: "You served with Edmund decades ago. Dr. Finch is your card partner.",
      reasonPresent: "An annual visit.",
      motive: "Edmund owed you money from an old wager, and never paid.",
      suspicious: "You were alone in the drawing room for stretches of the evening.",
      secret: null,
      knows: [
        "You played cards with Dr. Finch in the drawing room from 21:00. He left twice: around 21:50 to 22:00, and around 22:25 to 22:35.",
        "The second time he came back he smelled of smoke.",
      ],
      culprit: false,
    },
    {
      id: "C6",
      name: "Edward Thorne",
      blurb: "Lord Blackwood's solicitor",
      background: "You've handled the Blackwood family's legal affairs for decades.",
      relationship: "You drew up Edmund's will. You distrust Jasper.",
      reasonPresent: "Edmund summoned you to discuss changes to his will.",
      motive: "Edmund discovered you'd been overcharging the estate.",
      suspicious: "You were meant to meet Edmund at 22:00, but the meeting never happened.",
      secret: "Edmund had found out you'd been overbilling the estate for years. He was going to take his business elsewhere.",
      knows: [
        "At 22:00 you went to the study for your meeting, but Dr. Finch was just leaving and said Edmund was 'resting'. You went away.",
        "Edmund told you at dinner he intended to 'settle an ugly matter with an old friend'.",
      ],
      culprit: false,
    },
    {
      id: "C7",
      name: "Rosie Pell",
      blurb: "the manor's young maid",
      background: "You started at the manor three months ago.",
      relationship: "Mrs. Hodge is your boss. You're sweet on the stable boy.",
      reasonPresent: "You live in at the manor.",
      motive: "Lord Blackwood shouted at you last week and threatened to dismiss you.",
      suspicious: "You were seen hurrying along the study corridor.",
      secret: null,
      knows: [
        "At about 22:20 you saw a light flickering in the study fireplace, though the fire had been let die earlier.",
        "Duchess the hen got out of the kitchen yard again at about 21:30.",
      ],
      culprit: false,
    },
    {
      id: "C8",
      name: "Harold Vance",
      blurb: "the Blackwoods' chauffeur",
      background: "You've driven for the family for fifteen years.",
      relationship: "Lady Margaret confides in you. Jasper owes you money.",
      reasonPresent: "On call to drive guests home, though the storm cancelled that.",
      motive: "Lord Blackwood cut your wages.",
      suspicious: "You spent the evening in the garage, which has a door into the garden.",
      secret: null,
      knows: [
        "Lady Margaret asked you on Friday to keep a suitcase in the car boot. You didn't ask why.",
        "At about 21:35 you saw Jasper hurrying across the garden toward the gate.",
      ],
      culprit: false,
    },
  ],
  truth:
    "Dr. Alistair Finch poisoned Lord Blackwood with digitalis from his own bag during a 21:50 'consultation', because Edmund was about to report his forged prescriptions. At 22:25 he borrowed matches from Mrs. Hodge and tried to burn Edmund's letter, but it only half burned. The stopped clock simply ran down, the muddy footprint and the open French window were Jasper sneaking out to pay his bookie, and the chicken was Mrs. Hodge's hen, who wandered in through that window.",
  chain: [
    { id: "letter", description: "Letter threatening the Medical Council", keywords: ["medical council", "letter", "note", "burn"] },
    { id: "digitalis", description: "Digitalis is a doctor's drug", keywords: ["digitalis", "bag", "prescription"] },
    { id: "study", description: "Seen entering the study 21:50-22:00", keywords: ["21:50", "study", "pale", "consultation"] },
    { id: "matches", description: "Borrowed matches at 22:25 and left the game twice", keywords: ["matches", "22:25", "smoke", "left twice", "card"] },
  ],
};
