import type { Case } from "../types";

// Culprit: Rafael Moreno (C2).
// The evidence alone does NOT name Rafael: the alarm card (E1) could belong to curatorial, restoration, security
// or IT, and the wax (E2) is used by curatorial staff too. Testimony decides it: Dana approved maintenance mode
// at Rafael's request -> Theo saw Rafael hurrying from the Egyptian wing wiping his hands at 20:20 ->
// Marguerite smelled wax by the wing at 20:00 and saw Rafael sitting very still at 20:25.
export const museumHeist: Case = {
  id: "museum-heist",
  title: "The Museum Heist",
  description:
    "During a private donor preview at the Aldermoor Museum, the Golden Scarab brooch disappeared from its locked case in the Egyptian wing. The alarm never sounded. Everyone in the building had a reason to be near it.",
  setting: "The Aldermoor Museum's after-hours donor preview",
  victim: "The Aldermoor Museum (the Golden Scarab brooch was stolen)",
  timeline: { start: "19:30", end: "21:00" },
  evidence: [
    {
      id: "E1",
      title: "Alarm log",
      text: "The Scarab case alarm was switched to 'maintenance mode' from 20:05 to 20:25 with a collections-wing staff card. The log records the card type, not whose it was. Cards like this are issued to curatorial, restoration, security and IT staff.",
      kind: "key",
      explanation: "Rafael used his own restoration card after asking Dana to approve maintenance mode for a 'scheduled wax treatment'. Beatrice, Dana and Oscar hold the same card type.",
    },
    {
      id: "E2",
      title: "Wax on the latch",
      text: "Fresh smudges of microcrystalline conservator's wax on the Scarab case latch. Curatorial staff use the same wax to polish display cases, and restoration staff use it on objects.",
      kind: "key",
      explanation: "Rafael had wax on his fingers from the workshop when he opened the latch. Beatrice also handles the wax, which is why it does not point at one person.",
    },
    {
      id: "E3",
      title: "Torn black glove",
      text: "A scrap of torn black fabric from a serving glove, caught on the Egyptian wing's staff door.",
      kind: "ambiguous",
      explanation: "Theo tore his glove sneaking through the staff door at 20:30 to photograph the empty case for his article.",
    },
    {
      id: "E4",
      title: "Pawn receipt",
      text: "A pawn shop receipt for a pearl necklace, dated yesterday, found in the donors' cloakroom.",
      kind: "red_herring",
      explanation: "Lady Imogen pawned her pearls. She's broke and hiding it from society. It has nothing to do with the Scarab.",
    },
    {
      id: "E5",
      title: "The pigeon",
      text: "A live pigeon was found perched on a sarcophagus in the Egyptian wing, looking extremely pleased with itself.",
      kind: "odd",
      explanation: "Theo propped the roof fire door open for a cigarette at 19:45 and a pigeon wandered in. Nothing to do with the theft.",
    },
  ],
  characters: [
    {
      id: "C1",
      name: "Beatrice Crane",
      blurb: "the museum's head curator",
      background: "You've curated the Egyptian collection for twenty years. The Scarab is your pride.",
      relationship: "Rafael restores pieces for you. Lady Imogen is your most important donor.",
      reasonPresent: "Hosting the donor preview.",
      motive: "The board is cutting your department. A dramatic theft would bring headlines, sympathy and funding.",
      suspicious: "You have keys to every case in the wing.",
      secret: "Last week you cracked the Scarab case's glass while cleaning and covered the crack with a label instead of reporting it. You're terrified the investigation will find it.",
      knows: [
        "At about 19:50 you saw Lady Imogen standing alone at the Scarab case for several minutes.",
        "Rafael told you this afternoon he'd be 'working late in the workshop'.",
      ],
      culprit: false,
    },
    {
      id: "C2",
      name: "Rafael Moreno",
      blurb: "the museum's art restorer",
      background: "You're a gifted restorer. Very few people know you also make forgeries for private collectors.",
      relationship: "You work for Beatrice. Dana handles your access requests.",
      reasonPresent: "You said you were working late in the restoration workshop.",
      motive: "You owe a dangerous collector a lot of money, and he wants the Scarab.",
      suspicious: "Your department's card is in the alarm log, and your hands smell of wax.",
      secret: null,
      knows: [
        "Theo the waiter keeps wandering where waiters shouldn't be.",
        "Beatrice has been acting nervous around the Scarab case all week.",
      ],
      culprit: true,
      whatYouDid: [
        "At 19:55 you asked Dana to approve maintenance mode on the Scarab case for a 'scheduled wax treatment'. She said yes over the phone.",
        "At 20:05 you switched the alarm to maintenance mode with your restoration card.",
        "At about 20:15 you opened the latch, with wax still on your fingers, and pocketed the Scarab.",
        "You hid it inside a hollow plaster cast in the workshop and were back at your bench by 20:25.",
      ],
      looseEnds: [
        "Dana knows you requested maintenance mode.",
        "The wax on the latch is restoration wax.",
        "Someone may have seen you walking back from the Egyptian wing.",
      ],
    },
    {
      id: "C3",
      name: "Lady Imogen Fairfax",
      blurb: "the museum's wealthiest donor",
      background: "Old family, famous parties, and a fortune that's quietly gone.",
      relationship: "Beatrice relies on your donations.",
      reasonPresent: "Guest of honour at the preview.",
      motive: "You desperately need money, and the Scarab is priceless.",
      suspicious: "You lingered alone at the Scarab case. The pawn receipt in the cloakroom is yours.",
      secret: "You're broke. Yesterday you pawned your pearls to pay for tonight's dress. If anyone finds out, you're finished in society.",
      knows: [
        "At about 20:30 you saw a waiter, Theo, slip through the staff door into the Egyptian wing.",
        "You admired the Scarab at 19:50 because your grandmother once owned one like it.",
      ],
      culprit: false,
    },
    {
      id: "C4",
      name: "Theo Park",
      blurb: "a waiter working the preview",
      background: "You're not really a waiter. You're a journalist working undercover on a story about the museum's finances.",
      relationship: "You've been watching Beatrice and Rafael for weeks.",
      reasonPresent: "Serving drinks, officially.",
      motive: "A theft would make your story explode.",
      suspicious: "You kept leaving your post to take photos. The torn glove on the staff door is yours, and you propped the roof door open. You'd happily tell the detective you're a journalist if it came to it.",
      secret: null,
      knows: [
        "At about 20:20 you saw Rafael walking fast from the Egyptian wing toward the workshop, wiping his hands on a cloth.",
        "At 19:45 you propped the roof fire door open for a cigarette.",
      ],
      culprit: false,
    },
    {
      id: "C5",
      name: "Dana Holt",
      blurb: "the museum's head of security",
      background: "Ex-police. You run a tight ship, most of the time.",
      relationship: "You approve access requests from every department.",
      reasonPresent: "Running security for the preview.",
      motive: "You were passed over for a raise and you've complained loudly about it.",
      suspicious: "You approved switching off the alarm.",
      secret: null,
      knows: [
        "At 19:55 Rafael phoned asking you to approve maintenance mode on the Scarab case for a 'scheduled wax treatment'. You approved it without checking the schedule, which is embarrassing.",
        "At 21:00 you found the case closed and the Scarab gone.",
      ],
      culprit: false,
    },
    {
      id: "C6",
      name: "Felix Grant",
      blurb: "a society photographer covering the preview",
      background: "You photograph every party worth being seen at.",
      relationship: "Lady Imogen is your best subject. You find Beatrice stuffy.",
      reasonPresent: "Photographing the donors for a magazine.",
      motive: "A photo of the empty case would sell for a fortune.",
      suspicious: "You wandered the galleries with a camera all evening.",
      secret: "You slipped into the closed Egyptian wing at 19:40 to shoot the Scarab without permission. If it comes out, you'll be banned from every museum in the city.",
      knows: [
        "Your camera timestamps show the Scarab still in its case at 19:40.",
        "At about 20:10 you saw Dana on her phone near the security desk, looking distracted.",
      ],
      culprit: false,
    },
    {
      id: "C7",
      name: "Marguerite Olsen",
      blurb: "a retired Egyptologist and museum volunteer",
      background: "Forty years digging in Egypt. Now you give tours for free.",
      relationship: "You trained Beatrice. You think Rafael's restorations are a bit too perfect.",
      reasonPresent: "Giving short talks to the donors.",
      motive: "You believe the Scarab should be returned to Egypt.",
      suspicious: "You've publicly campaigned for the Scarab's repatriation.",
      secret: null,
      knows: [
        "At about 20:00 you smelled restoration wax in the corridor outside the Egyptian wing.",
        "Rafael's workshop door was ajar at 20:25, and he was sitting very still at his bench.",
      ],
      culprit: false,
    },
    {
      id: "C8",
      name: "Oscar Linde",
      blurb: "the museum's IT technician",
      background: "You keep the museum's systems running, including the alarms.",
      relationship: "Dana is your boss. You help Rafael with his access card when it glitches.",
      reasonPresent: "On call in case the ticketing system crashed.",
      motive: "You know the alarm system better than anyone.",
      suspicious: "You could switch any alarm off from your laptop.",
      secret: null,
      knows: [
        "The alarm system can only be put in maintenance mode with a department card at the case panel, not remotely.",
        "You were in the server room fixing the Wi-Fi from 19:50 to 20:40.",
      ],
      culprit: false,
    },
  ],
  truth:
    "Rafael Moreno stole the Golden Scarab to pay off a collector he forges for. He talked Dana into approving maintenance mode, switched off the case alarm with his restoration card at 20:05, opened the latch with wax still on his fingers, and hid the brooch in a hollow plaster cast in his workshop. Beatrice was hiding a cracked case, Lady Imogen was hiding that she's broke, and Theo was an undercover journalist whose wanderings, torn glove and propped door (hello, pigeon) made him look guilty.",
  chain: [
    { id: "alarm", description: "Maintenance mode with a collections-wing card", keywords: ["maintenance", "card", "alarm", "20:05"] },
    { id: "wax", description: "Conservator's wax on the latch", keywords: ["wax", "latch"] },
    { id: "request", description: "Dana approved Rafael's request", keywords: ["approve", "request", "wax treatment", "schedule"] },
    { id: "sighting", description: "Theo saw Rafael leaving the wing wiping his hands", keywords: ["wiping", "hands", "20:20", "workshop"] },
  ],
};
