import type { Case } from "../types";

// Culprit: Leon Marchetti (C1).
// The evidence alone does NOT name Leon: the white hairs (E2) could be a violin bow or Barnaby's stage wig, and the
// key in the sugar bowl (E1) only points at the dining car crowd. Testimony decides it: Anya saw Leon loitering by
// the key hook at 12:30 AM -> Clara heard a thud at 12:42 AM and someone humming -> Barnaby and Ines saw Leon return
// to the dining car at about 12:50 AM -> Father Tomas saw Leon walking toward the sleeping carriages at 12:35 AM.
export const nightTrain: Case = {
  id: "night-train",
  title: "Murder on the Night Train",
  description:
    "Somewhere between Vienna and Budapest, the jewel dealer Viktor Sorel was found dead in sleeping compartment 7, and his famous blue diamond was gone. The train didn't stop all night. The killer is still aboard.",
  setting: "The Danube Express sleeper train, overnight",
  victim: "Viktor Sorel, jewel dealer",
  timeline: { start: "11:30 PM", end: "1:30 AM" },
  evidence: [
    {
      id: "E1",
      title: "Missing spare key",
      text: "The conductor's spare key for compartment 7 was missing from its hook between 12:30 AM and 1:00 AM. It turned up in the dining car's sugar bowl.",
      kind: "key",
      explanation: "Leon lifted it at 12:30 AM while chatting to Anya, and dropped it in the sugar bowl when he returned at 12:50 AM.",
    },
    {
      id: "E2",
      title: "Horsehair on the latch",
      text: "A few long white hairs were caught in compartment 7's door latch. They could be horsehair, or hair from a stage wig.",
      kind: "key",
      explanation: "Violin bow hair. Leon's bow was tucked under his arm when he forced the latch. Barnaby's white stage wig made him an equally good suspect on this clue alone.",
    },
    {
      id: "E3",
      title: "The tunnel",
      text: "The train passed through the long Semmering tunnel from 12:38 AM to 12:46 AM. The corridor lights flickered off the whole way.",
      kind: "ambiguous",
      explanation: "It gave the killer cover, but it also means nobody's sightings in that window are reliable.",
    },
    {
      id: "E4",
      title: "Torn passport page",
      text: "A torn passport page, the name smudged, was found in the bin of compartment 5.",
      kind: "red_herring",
      explanation: "Clara tore out her real name. She's travelling on a fake identity to escape her family.",
    },
    {
      id: "E5",
      title: "The goldfish",
      text: "A goldfish was found swimming in a champagne bucket on a dining car table.",
      kind: "odd",
      explanation: "Barnaby's 'vanishing goldfish' trick from the evening show. He forgot to vanish it back.",
    },
  ],
  characters: [
    {
      id: "C1",
      name: "Leon Marchetti",
      blurb: "a travelling concert violinist",
      background: "A talented violinist from an old family that lost everything.",
      relationship: "Viktor cheated your grandfather out of the blue diamond fifty years ago. Viktor doesn't know who you are.",
      reasonPresent: "Travelling to a concert in Budapest. You played for the dining car this evening.",
      motive: "You wanted your family's diamond back.",
      suspicious: "You were near the conductor's station tonight, and your bow is strung with white horsehair.",
      secret: null,
      knows: [
        "Viktor's assistant Greta seemed nervous all evening.",
        "Barnaby the magician was in the dining car practising tricks.",
      ],
      culprit: true,
      whatYouDid: [
        "At 12:30 AM you chatted to Anya the conductor at her station and lifted the spare key for compartment 7 from the hook.",
        "When the train entered the tunnel at 12:38 AM, you went to compartment 7 with your bow under your arm. Viktor woke and struggled, and you struck him. You took the diamond.",
        "You hummed to steady your nerves as you walked back. You returned to the dining car at about 12:50 AM and dropped the key in the sugar bowl.",
        "The diamond is hidden in the lining of your violin case.",
      ],
      looseEnds: [
        "Anya may remember you by her key hook.",
        "Your bow sheds white horsehair.",
        "Someone might have heard you humming.",
      ],
    },
    {
      id: "C2",
      name: "Anya Petrova",
      blurb: "the train's conductor",
      background: "Twenty years on the Danube Express. You know every creak of this train.",
      relationship: "You look after everyone aboard. Viktor tipped badly.",
      reasonPresent: "Working the night shift.",
      motive: "Viktor complained about you to the rail company last month.",
      suspicious: "The spare key went missing from your station and you didn't notice until morning, because you dozed off there from about 12:35 AM to 1:00 AM.",
      secret: null,
      knows: [
        "At about 12:30 AM Leon the violinist stood by your key hook chatting about arrival times for longer than necessary.",
        "Viktor asked you at 11:40 PM not to disturb him before morning.",
      ],
      culprit: false,
    },
    {
      id: "C3",
      name: "Clara Moreau",
      blurb: "a young woman travelling alone in compartment 5",
      background: "The runaway daughter of a powerful family.",
      relationship: "You'd never met Viktor. Your compartment is next to his.",
      reasonPresent: "Getting as far from home as possible.",
      motive: "A diamond like that would fund a new life.",
      suspicious: "You're right next door to compartment 7. The torn passport page is yours.",
      secret: "You're travelling under a false name to escape your family. You tore your real name out of your passport. If it comes out, they'll find you.",
      knows: [
        "At about 12:42 AM, in the tunnel, you heard a heavy thud from compartment 7, then someone humming a tune in the corridor.",
        "You didn't open your door. You were too scared.",
      ],
      culprit: false,
    },
    {
      id: "C4",
      name: "Barnaby Quill",
      blurb: "a retired stage magician",
      background: "Forty years on stage as 'The Great Quillini'. Still can't resist an audience.",
      relationship: "You performed for the dining car tonight, after Leon played.",
      reasonPresent: "Heading to a magicians' convention in Budapest.",
      motive: "You're good with locks and misdirection, and your pension is tiny.",
      suspicious: "Everyone knows you can pick a lock. You wear a long white wig on stage. The goldfish is yours.",
      secret: null,
      knows: [
        "You stayed in the dining car practising card tricks from 12:00 AM until about 1:00 AM.",
        "At about 12:50 AM Leon came back into the dining car from the sleeping carriages, breathing hard, and sat down next to the sugar bowl.",
      ],
      culprit: false,
    },
    {
      id: "C5",
      name: "Greta Lind",
      blurb: "Viktor Sorel's personal assistant",
      background: "You've managed Viktor's diary and accounts for eight years.",
      relationship: "Viktor's employee. You know all his business.",
      reasonPresent: "Travelling with Viktor to a diamond sale in Budapest.",
      motive: "Viktor was about to sell the diamond and retire, leaving you with nothing.",
      suspicious: "You had access to Viktor at any time, and you're his closest contact.",
      secret: "You've been skimming money from Viktor's accounts for years. Any look at his finances will expose you.",
      knows: [
        "At 11:45 PM Viktor told you he was expecting a visitor about 'a family matter from the old days', and laughed about it.",
        "You were in your compartment, number 3, from midnight onwards.",
      ],
      culprit: false,
    },
    {
      id: "C6",
      name: "Father Tomas Novak",
      blurb: "a priest travelling to a conference",
      background: "A kindly priest who can't sleep on trains.",
      relationship: "You chatted with Viktor at dinner. You found him cold.",
      reasonPresent: "Travelling to a church conference in Budapest.",
      motive: "Viktor mocked your faith at dinner in front of everyone.",
      suspicious: "You wandered the corridors during the night.",
      secret: "You're not only travelling for the conference. You're delivering a large cash donation you've been quietly skimming from for years to pay gambling debts.",
      knows: [
        "At about 12:35 AM you saw Leon walk from the conductor's station toward the sleeping carriages with his violin bow under his arm.",
        "Clara looked frightened at dinner whenever anyone asked her name.",
      ],
      culprit: false,
    },
    {
      id: "C7",
      name: "Ines Varga",
      blurb: "the dining car attendant",
      background: "You've served dinner on the Danube Express for five years.",
      relationship: "Anya is your friend. Barnaby tips well.",
      reasonPresent: "Working the late shift in the dining car.",
      motive: "Viktor accused you of stealing from his table and got your pay docked.",
      suspicious: "You had keys to every cupboard in the dining car.",
      secret: null,
      knows: [
        "Leon left the dining car at about 12:25 AM and came back at about 12:50 AM, flushed.",
        "When you cleared tables at 1:05 AM you found the sugar bowl lid askew.",
      ],
      culprit: false,
    },
    {
      id: "C8",
      name: "Dmitri Orlov",
      blurb: "a businessman in compartment 9",
      background: "An exporter who travels this line every month.",
      relationship: "You've done deals with Viktor before, and lost money on them.",
      reasonPresent: "A business trip.",
      motive: "Viktor cheated you on a diamond deal last year.",
      suspicious: "You had a loud argument with Viktor in the corridor at 11:50 PM.",
      secret: null,
      knows: [
        "You argued with Viktor at 11:50 PM about an old deal, then went to your compartment and stayed there.",
        "Your compartment is at the far end of the carriage. You heard nothing in the tunnel.",
      ],
      culprit: false,
    },
  ],
  truth:
    "Leon Marchetti killed Viktor Sorel to take back the blue diamond Viktor cheated his grandfather out of. He lifted the spare key from Anya's station at 12:30 AM, struck Viktor during the tunnel, and left bow hair on the latch. He hummed on his way back, where Clara heard him, then dropped the key in the sugar bowl at 12:50 AM, which Barnaby saw. The diamond is in his violin case lining. Clara's torn passport was about escaping her family, and the goldfish was Barnaby's forgotten trick.",
  chain: [
    { id: "key", description: "Spare key lifted at 12:30 AM and found in the sugar bowl", keywords: ["key", "hook", "sugar bowl", "12:30 AM"] },
    { id: "bow", description: "White hair: violin bow or a stage wig", keywords: ["hair", "horsehair", "bow", "violin", "wig"] },
    { id: "humming", description: "Thud at 12:42 AM then humming", keywords: ["hum", "thud", "12:42 AM", "tune"] },
    { id: "return", description: "Returned to the dining car at 12:50 AM", keywords: ["12:50 AM", "dining car", "breathing hard"] },
  ],
};
