import type { Case } from "../types";

// Culprit: Dr. Elena Voss (C1).
// The evidence alone does NOT name Elena: the master code (E1) fits four people and the shutdown log (E2) only
// says the thief wanted Wren intact. Testimony decides it: Marcus's stairwell call is corroborated by Victor ->
// Kenji was seen alone in the break room -> Priya says Elena sent her home and offered to lock up -> Sam saw a
// heavy laptop bag at a silver hatchback at 9:25 PM -> the duck (E5) is Elena's joke (Priya and Tom know it).
export const stolenPrototype: Case = {
  id: "stolen-prototype",
  title: "The Stolen Prototype",
  description:
    "The night before its big launch, Helix Robotics discovered that Wren, its prototype robotic hand, had vanished from a locked lab. Only a handful of people were still in the building. Somebody walked out with the company's future.",
  setting: "Helix Robotics headquarters, the night before launch",
  victim: "Helix Robotics (the Wren prototype was stolen)",
  timeline: { start: "8:00 PM", end: "10:00 PM" },
  evidence: [
    {
      id: "E1",
      title: "Lab keypad log",
      text: "The lab door was opened at 9:14 PM with a master code. The keypad log records that a master code was used, not whose. A handful of senior Helix people and the visiting contractor have one.",
      kind: "key",
      explanation: "Elena used her own master code. Marcus was on the phone in the stairwell, Sam was on the phone with his daughter, and Kenji was debugging alone upstairs.",
    },
    {
      id: "E2",
      title: "Calibration rig log",
      text: "Wren was switched off cleanly at 9:12 PM before it was removed. Yanking it out would have fried it, so the thief did not want it damaged.",
      kind: "key",
      explanation: "The thief wanted Wren intact. Elena designed it and refused to see it damaged. Many people could have read the runbook, so this only shows care, not who.",
    },
    {
      id: "E3",
      title: "Warm coffee cup",
      text: "A coffee cup with the Helix logo on the lab bench, still slightly warm when security checked at 10:00 PM.",
      kind: "ambiguous",
      explanation: "Priya's cup. She left it at 8:50 PM when Elena sent her home. It was in a thermal mug sleeve, which kept it warm. Nadia and Priya both carry Helix cups, so it points at no one.",
    },
    {
      id: "E4",
      title: "Rival's business card",
      text: "A business card from Orbital Dynamics, Helix's main rival, found on the floor of the parking garage.",
      kind: "red_herring",
      explanation: "Victor dropped it. He met Orbital earlier that day to hedge his investment, which he's hiding from Marcus.",
    },
    {
      id: "E5",
      title: "The duck",
      text: "A rubber duck wearing a tiny hard hat was sitting in Wren's empty case.",
      kind: "odd",
      explanation: "The engineering team's mascot 'Quacksworth', which lives on Elena's desk. She left it in the case as a private goodbye joke.",
    },
  ],
  characters: [
    {
      id: "C1",
      name: "Dr. Elena Voss",
      blurb: "a member of the Wren team",
      background: "You spent six years building Wren. It's the best work of your life.",
      relationship: "You co-founded the lab with Marcus but he now controls the company. You mentor Priya.",
      reasonPresent: "Final calibration of Wren before tomorrow's launch.",
      motive: "You found out Marcus plans to sell Wren's patents to a defense contractor. You swore Wren would never become a weapon.",
      suspicious: "You have a master code, you know the shutdown sequence, and you drive a silver hatchback.",
      secret: null,
      knows: [
        "Priya was working in the lab until about 8:45 PM.",
        "Marcus kept disappearing to take phone calls tonight.",
      ],
      culprit: true,
      whatYouDid: [
        "At 8:45 PM you told Priya to go home and said you'd lock up.",
        "At 9:12 PM you ran Wren's shutdown sequence remotely, and at 9:14 PM you opened the lab with your master code.",
        "You packed Wren into your laptop bag, left the duck in the empty case, and carried the bag to your car in the garage at about 9:25 PM.",
        "You were back at your desk by 9:35 PM.",
      ],
      looseEnds: [
        "The keypad log shows a master code, and only you and Marcus have one.",
        "Priya knows you sent her home and offered to lock up.",
        "The security guard might have seen someone in the garage.",
        "Everyone knows the duck lives on your desk.",
      ],
    },
    {
      id: "C2",
      name: "Marcus Hale",
      blurb: "Helix's CEO",
      background: "You turned a garage lab into a company worth hundreds of millions, and you did it by making hard deals.",
      relationship: "Elena is your co-founder and increasingly your critic. Victor is your biggest investor.",
      reasonPresent: "Rehearsing tomorrow's launch speech.",
      motive: "Wren is insured for far more than the company could sell it for right now.",
      suspicious: "You have a master code. From 9:05 PM to 9:20 PM you left your office and nobody at Helix knows where you went.",
      secret: "From 9:05 PM to 9:20 PM you were in the stairwell on a call with a defense contractor, secretly negotiating to sell Wren's patents. If Elena or Victor found out, it would blow up the company.",
      knows: [
        "At about 9:05 PM, on your way to the stairwell, you saw Elena walking toward the lab corridor.",
        "Victor has been cagey all day about where he was this morning.",
      ],
      culprit: false,
    },
    {
      id: "C3",
      name: "Priya Nair",
      blurb: "a junior engineer on the Wren team",
      background: "You're 24, brilliant, and desperate to impress.",
      relationship: "Elena is your mentor and hero.",
      reasonPresent: "Finishing Wren's grip-sensor code before launch.",
      motive: "You were passed over for the launch team and it stung.",
      suspicious: "You were the last person seen in the lab. The warm coffee cup on the bench is yours.",
      secret: null,
      knows: [
        "At about 8:45 PM Elena told you to go home and said she'd lock the lab herself. That was unusual. She never locks up.",
        "You left the lab at 8:50 PM and caught the 9:05 PM bus. Your bus pass will show it.",
        "Quacksworth the duck always sits on Elena's desk.",
      ],
      culprit: false,
    },
    {
      id: "C4",
      name: "Victor Lang",
      blurb: "Helix's largest investor",
      background: "You've backed a dozen startups. Helix is your biggest bet.",
      relationship: "Marcus answers to you. You find Elena difficult.",
      reasonPresent: "Watching the launch rehearsal.",
      motive: "If Wren fails at launch, your investment tanks. You might prefer Orbital to have it.",
      suspicious: "The Orbital business card in the garage is yours.",
      secret: "This morning you secretly met Orbital Dynamics about investing in them too. If Marcus finds out, he'll say you betrayed Helix.",
      knows: [
        "At about 9:15 PM you passed the stairwell and heard Marcus on the phone, talking about 'the patents'.",
        "You parked in the garage at 7:30 PM. Elena's silver hatchback was parked near the lift.",
      ],
      culprit: false,
    },
    {
      id: "C5",
      name: "Sam Ortiz",
      blurb: "the night security guard",
      background: "Twelve years in building security. You've never lost anything on your watch.",
      relationship: "You know everyone by their car.",
      reasonPresent: "Your regular night shift.",
      motive: "Money's tight, and a prototype would fetch a fortune.",
      suspicious: "You were supposed to do a round at 9:00 PM, but you did it late because you were on the phone with your daughter.",
      secret: null,
      knows: [
        "At about 9:25 PM on your late round you saw someone at a silver hatchback in the garage putting a heavy laptop bag in the boot. You didn't see their face.",
        "At 10:00 PM you found the lab locked, with the duck sitting in the empty case.",
      ],
      culprit: false,
    },
    {
      id: "C6",
      name: "Nadia Brooks",
      blurb: "Helix's head of communications",
      background: "You've spent months building hype for tomorrow's launch.",
      relationship: "You report to Marcus. You find Elena brilliant but impossible to manage.",
      reasonPresent: "Finalising the launch press kit.",
      motive: "A stolen prototype would be a PR disaster, but also the biggest story of your career.",
      suspicious: "You were walking the corridors all evening with no fixed desk.",
      secret: "You've been quietly leaking launch details to a tech journalist in exchange for a flattering profile. If Marcus finds out, you're fired.",
      knows: [
        "At about 9:10 PM you saw Marcus hurry into the stairwell holding his phone to his ear.",
        "You texted a journalist from the break room at 9:20 PM.",
      ],
      culprit: false,
    },
    {
      id: "C7",
      name: "Tom Reyes",
      blurb: "the evening contract cleaner",
      background: "You clean three office buildings a night and notice everything.",
      relationship: "You chat with Sam the guard most nights. You barely know the engineers.",
      reasonPresent: "Your regular cleaning shift.",
      motive: "You're behind on rent, and everyone knows the prototype is valuable.",
      suspicious: "Your cleaning cart was parked near the lab corridor around 9:00 PM.",
      secret: null,
      knows: [
        "At about 9:30 PM you emptied the bin at Elena's desk. The desk was empty and the little duck that always sits there was gone.",
        "You saw Priya leave through the front doors just before 9:00 PM.",
      ],
      culprit: false,
    },
    {
      id: "C8",
      name: "Kenji Mori",
      blurb: "a visiting firmware contractor",
      background: "A freelance engineer hired for two weeks to tidy up Wren's firmware.",
      relationship: "You work under Elena. Victor recommended you to Helix.",
      reasonPresent: "Pushing a last-minute firmware fix.",
      motive: "Orbital has offered you a full-time job, and they'd love Wren.",
      suspicious: "You were in the building late with a laptop full of Wren's firmware.",
      secret: null,
      knows: [
        "You were in the second-floor break room from 9:00 PM to 9:30 PM debugging, alone.",
        "At about 9:15 PM you heard the lab door's keypad beep twice from down the corridor.",
      ],
      culprit: false,
    },
  ],
  truth:
    "Elena Voss stole Wren to stop Marcus from selling it as a weapon. She sent Priya home at 8:45 PM, powered Wren down with the proper sequence at 9:12 PM, opened the lab with her master code at 9:14 PM, and carried Wren out in her laptop bag to her silver hatchback at 9:25 PM, leaving the team duck as a goodbye. Marcus's missing fifteen minutes were a secret call to sell the patents, which is why he was evasive. Victor was hiding a meeting with Orbital. Sam's late round only looked suspicious.",
  chain: [
    { id: "master-code", description: "Master code at 9:14 PM fits Elena, Marcus, Sam or Kenji", keywords: ["master code", "keypad", "9:14 PM"] },
    { id: "sent-home", description: "Elena sent Priya home and offered to lock up", keywords: ["sent", "go home", "lock up", "lock the lab"] },
    { id: "garage", description: "Heavy laptop bag at a silver hatchback at 9:25 PM", keywords: ["hatchback", "laptop bag", "garage", "boot", "9:25 PM"] },
    { id: "duck", description: "The duck lives on Elena's desk", keywords: ["duck", "quacksworth"] },
  ],
};
